---
# tasks file for bind_config
- name: Update apt package cache
  become: true
  apt:
    update_cache: yes

- name: Install bind package
  become: true
  apt:
    name: bind9
    state: present

- name: Include hosts vars
  include_vars:
    file: "/home/ubuntu/ansible-playbooks/inventories/zones_data.yaml"
    name: hosts_data
 
- name: Create named.conf
  template:
    src: "{{ role_path }}/templates/named.conf.j2"
    dest: /etc/bind/named.conf

- name: Create domain zone files
  template:
    src: "{{ role_path }}/templates/lookup_file.conf.j2"
    dest: "/etc/bind/zones/{{ item.key }}.zone"
  loop: "{{ hosts_data.configs }}"
  loop_control:
    loop_var: item

- name: Create reverse lookup zone files
  template:
    src: "{{ role_path }}/templates/reverse_lookup_file.conf.j2"
    dest: "/etc/bind/zones/{{ item.key.split('.')[-2] }}.zone"
  loop: "{{ hosts_data.configs }}"
  loop_control:
    loop_var: item

- name: Ensure named service is running and enabled
  service:
    name: named
    state: started
    enabled: yes

