---
# tasks file for bind_config
- name: Update apt package cache
  become: true
  apt:
    update_cache: yes

- name: Install bind package
  become: true
  apt:
    name: bind9
    state: present

- name: Include hosts vars
  include_vars:
    file: "/home/ubuntu/ansible-playbooks/inventories/zones_data.yaml"
    name: hosts_data
 
- name: Create named.conf
  become: true
  template:
    src: "{{ role_path }}/templates/named.conf.j2"
    dest: /etc/bind/named_.conf

- name: Create domain zone files
  become: true
  template:
    src: "{{ role_path }}/templates/lookup.conf.j2"
    dest: "/etc/bind/{{ item.zone }}.zone"
  loop: "{{ hosts_data.configs }}"

- name: Create reverse lookup zone files
  become: true
  template:
    src: "{{ role_path }}/templates/reverse_lookup.conf.j2"
    dest: "/etc/bind/{{ item.reverse_zone.split('.')[-2] }}.zone"
  loop: "{{ hosts_data.configs }}"

- name: Ensure named service is running and enabled
  service:
    name: named
    state: started
    enabled: yes

